# Generated by Django 4.2.4 on 2023-08-13 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_image_height_image_location_image_number_of_channels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='location',
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='location',
        ),
    ]
