# Generated by Django 4.2.4 on 2023-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_image_location_remove_pdf_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='number_of_channels',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='num_pages',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='page_height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='page_width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
